version: "2.4"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      redis:
        condition: service_healthy
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
    volumes:
      - type: volume
        source: mydata
        target: /data
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 500m
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
volumes:
  mydata:
